services:
  - type: web
    name: quiz-results
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DB_DIR
        value: /data
    disk:
      name: sqlite-data
      mountPath: /data
      sizeGB: 1
